<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>使用promise 解决 异步同步加载 回调地狱的问题</title>
</head>
<body>
    <!-- 
        1. 什么是 Promise
            1， 异步编程的一种解决方案
        2. 回调地狱
            1. 在函数中使用回调函数，  在回调函数下继续使用回调函数
            $.ajax('url1', function(data1)) {
                $.ajax('url2', function(data1)) {
                    $.ajax('url3', function(data1)) {
                        $.ajax('url1', function(data1)) {
                            console.log(data4)
                        }
                    }
                }
            }

        3. 使用promise 解决 回调地狱
            1. Promise 是一个函数
                resolve 解决
                reject 拒绝

            new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve()   // 当成功调用时， 运行then函数
                },1000)
            }).then(()=> {
                console.log('第一次调用')
                console.log('第一次调用')
                ..... N次

                return new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve()
                    })
                }).then(()=> {
                    console.log('第二次调用')
                    console.log('第二次调用')
                    ..... N次

                    return new Promise((resolve, reject) => {
                        setTimeout(() => {
                            resolve()
                        })
                    }).then(()=> {
                        console.log('第三次调用')
                        console.log('第次调用')
                        ..... N次

                        return new Promise(....)
                    })
                })
            })

        4.  在解决异步调用函数时， 使用Promise 函数
            1. 创建 promise 函数， 传入 resolve,reject两个形参
            new Promise((resolve, reject) => {
                2.执行 定时器 异步调用
                setTImeout(() = > {
                    3. 当执行成功时， 调用resolve 函数, 并传入一个dat a信息
                    resolve('hellow word')
                    4. 如果失败， 调用reject函数，并传入一个err值
                    reject('console err')
                },1000)
            }).then(data => {               **** then() 与 catch() 是跟在promise后， 而不是settimeout()后
                console.log(data)
                console.log(data)
            }).catch(err => {
                console.log(err)
                console.log(err)
            })

        5. Promise的三种状态
            1. sync  同步
            2. async 异步   
                状态：  
                    1. pending  等待
                    2. fuilled  满足
                    3. rejected 拒绝
     -->


</body>
</html>